In [1]:
import sys
sys.path.append('d:/code/pywfn')
from pywfn.base import Mol
from pywfn.reader import LogReader
from pywfn.molprop import aromatic
import numpy as np

In [3]:
path=r"D:\gfile\zs\arom2.out"
mol=Mol(LogReader(path))
caler=aromatic.Calculator(mol)
caler.pisd_v1(),caler.pisd_v2(),caler.homed(),caler.pimed()

(0.1839156310002705,
 0.17687240769397405,
 0.9511558842295161,
 np.float64(0.8170302786094089))

In [2]:
path="D:\gfile\pywfn\C6H6.log"
mol=Mol(LogReader(path))
caler=aromatic.Calculator(mol)
caler.pisd_v1(),caler.pisd_v2(),caler.homed(),caler.pimed()

(5.354346986201501e-06,
 0.33027767111132883,
 0.9999992793124799,
 np.float64(0.9999992139767194))

In [4]:
path=r"D:\gfile\zs\arom3_lsp\2.log"
mol=Mol(LogReader(path))
caler=aromatic.Calculator(mol)
caler.pisd_v1(),caler.pisd_v2(),caler.homed(),caler.pimed()

(0.13678849437288296,
 0.20070953225904775,
 0.9540222770569508,
 np.float64(0.8714127848676368))

In [6]:
path=r"D:\gfile\zs\arom4_lsp\2.log"
mol=Mol(LogReader(path))
caler=aromatic.Calculator(mol)
caler.pisd_v1(),caler.pisd_v2(),caler.homed(),caler.pimed()

(0.12906965288597225,
 0.2063081238631017,
 0.9977234612173657,
 np.float64(0.8898256824326065))

In [7]:
path=r"D:\gfile\zs\arom5.log"
mol=Mol(LogReader(path))
caler=aromatic.Calculator(mol)
caler.pisd_v1(),caler.pisd_v2(),caler.homed(),caler.pimed()

(0.12412768062000368,
 0.22561899682712494,
 0.9958562758352243,
 np.float64(0.9236580949552166))

In [8]:
path=r"D:\gfile\zs\arom_ring18.log"
mol=Mol(LogReader(path))
caler=aromatic.Calculator(mol)
caler.pisd_v1(),caler.pisd_v2(),caler.homed(),caler.pimed()

(3.4733706319494324e-06,
 0.31632062389633575,
 0.9983271674402695,
 np.float64(0.9981292217692557))

In [8]:
from pywfn.bondprop import order
caler=order.Calculator(mol)
orders=caler.pi_pocv()[:,-1]
orders

array([0.6326, 0.6326, 0.0688, 0.6326, 0.0688, 0.6326, 0.0688, 0.6326,
       0.0688, 0.6326, 0.0688, 0.6326, 0.0688, 0.6326, 0.0688, 0.6326,
       0.0688, 0.6326, 0.0688, 0.6326, 0.0688, 0.6326, 0.0688, 0.6326,
       0.0688, 0.6326, 0.0688, 0.6326, 0.0688, 0.6326, 0.0688, 0.6326,
       0.0688, 0.6326, 0.0688, 0.0688])

In [9]:
for i in range(100):
    orders=np.random.rand(10)
    result=np.mean(orders)-np.std(orders)
    print(orders)
    print(result)

[0.064  0.621  0.2432 0.6404 0.0919 0.3547 0.5204 0.2343 0.665  0.3928]
0.17054665652716258
[0.7198 0.5282 0.7528 0.1852 0.0452 0.6993 0.9562 0.6914 0.7077 0.5453]
0.322430374310914
[0.951  0.7484 0.6631 0.0783 0.7482 0.5156 0.9013 0.7769 0.7659 0.5771]
0.43848253882040467
[0.2577 0.8664 0.9714 0.6513 0.2815 0.5536 0.0006 0.0492 0.7685 0.0541]
0.10157465789825143
[0.1962 0.8003 0.9737 0.5657 0.2233 0.1308 0.2762 0.3386 0.452  0.8212]
0.19482531259047714
[0.7984 0.2019 0.6428 0.9277 0.9468 0.3715 0.6537 0.4985 0.2451 0.4326]
0.3191561908939352
[0.3306 0.641  0.8654 0.4355 0.1674 0.492  0.0185 0.1369 0.1175 0.4459]
0.11450440338823925
[0.4662 0.5612 0.7883 0.9629 0.776  0.4892 0.6931 0.865  0.4623 0.2441]
0.4199380902907116
[0.3454 0.7858 0.0593 0.2444 0.8405 0.3572 0.3541 0.0556 0.2618 0.155 ]
0.08930472359898806
[0.2245 0.607  0.9983 0.1828 0.256  0.3517 0.1121 0.9484 0.0489 0.5822]
0.10989305808915406
[0.9927 0.1097 0.1406 0.6259 0.596  0.7862 0.2816 0.299  0.8146 0.7068]
0.2440077833

In [10]:
angs=np.linspace(0,360,19)[:-1]
r=4.15
cords=[]
for ang in angs:
    x=np.cos(ang/180*np.pi)*r
    y=np.sin(ang/180*np.pi)*r
    cords.append([x,y,0])
cords=np.array(cords)
for x,y,z in cords:
    print(f"C      {x:>16.8f} {y:>16.8f} {z:>16.8f}")

C            4.15000000       0.00000000       0.00000000
C            3.89972438       1.41938359       0.00000000
C            3.17908444       2.66756858       0.00000000
C            2.07500000       3.59400543       0.00000000
C            0.72063994       4.08695218       0.00000000
C           -0.72063994       4.08695218       0.00000000
C           -2.07500000       3.59400543       0.00000000
C           -3.17908444       2.66756858       0.00000000
C           -3.89972438       1.41938359       0.00000000
C           -4.15000000       0.00000000       0.00000000
C           -3.89972438      -1.41938359       0.00000000
C           -3.17908444      -2.66756858       0.00000000
C           -2.07500000      -3.59400543       0.00000000
C           -0.72063994      -4.08695218       0.00000000
C            0.72063994      -4.08695218       0.00000000
C            2.07500000      -3.59400543       0.00000000
C            3.17908444      -2.66756858       0.00000000
C            3

In [11]:
len(angs)

18

In [12]:
(1.45*18)/(2*np.pi)

4.153944014698468