# 键级计算
> 展示如何使用pywfn计算各种键级

In [1]:
import sys
sys.path.append('D:\code\pywfn')
from pywfn.base import Mol
from pywfn.reader import LogReader
from pywfn.bondprop import order

In [2]:
paths=[
  "D:\gfile\pywfn\C6H6.log"
]
mols=[Mol(LogReader(path)) for path in paths]

In [3]:
caler=order.Calculator(mols[0])

## mayer键级

In [4]:
caler.mayer()

array([[ 1.    ,  2.    ,  1.4533],
       [ 1.    ,  6.    ,  1.4533],
       [ 1.    ,  7.    ,  0.9305],
       [ 2.    ,  3.    ,  1.4533],
       [ 2.    ,  8.    ,  0.9305],
       [ 3.    ,  4.    ,  1.4533],
       [ 3.    ,  9.    ,  0.9305],
       [ 4.    ,  5.    ,  1.4533],
       [ 4.    , 10.    ,  0.9305],
       [ 5.    ,  6.    ,  1.4533],
       [ 5.    , 11.    ,  0.9305],
       [ 6.    , 12.    ,  0.9305]])

In [5]:
bonds=[
    [1,2],
    [2,3]
]
caler.dirMayer(bonds)

array([[ 1.    ,  2.    ,  0.    ,  0.    ,  1.    ,  0.6514],
       [ 1.    ,  2.    , -0.    , -0.    , -1.    ,  0.6514],
       [ 2.    ,  3.    ,  0.    ,  0.    , -1.    ,  0.6514],
       [ 2.    ,  3.    , -0.    , -0.    ,  1.    ,  0.6514]])

In [6]:
caler.boundMayer(1)

array([[ 1.    ,  2.    ,  0.    ,  0.    ,  1.    ,  0.873 ],
       [ 1.    ,  6.    ,  0.    ,  0.    ,  1.    ,  0.873 ],
       [ 1.    ,  7.    ,  0.    ,  0.    ,  1.    ,  0.2387],
       [ 1.    ,  2.    , -0.    , -0.    , -1.    ,  0.873 ],
       [ 1.    ,  6.    , -0.    , -0.    , -1.    ,  0.873 ],
       [ 1.    ,  7.    , -0.    , -0.    , -1.    ,  0.2387]])

In [7]:
caler.pi_pocv()

array([[ 1.    ,  2.    ,  0.6606],
       [ 1.    ,  6.    ,  0.6606],
       [ 1.    ,  7.    ,  0.    ],
       [ 2.    ,  3.    ,  0.6606],
       [ 2.    ,  8.    ,  0.    ],
       [ 3.    ,  4.    ,  0.6606],
       [ 3.    ,  9.    ,  0.    ],
       [ 4.    ,  5.    ,  0.6606],
       [ 4.    , 10.    ,  0.    ],
       [ 5.    ,  6.    ,  0.6606],
       [ 5.    , 11.    ,  0.    ],
       [ 6.    , 12.    ,  0.    ]])

In [8]:
caler.pi_smo(1,2)

np.float64(0.0)

In [9]:
caler.hmo()

array([[1.    , 2.    , 0.7422],
       [1.    , 3.    , 0.0669],
       [1.    , 4.    , 0.342 ],
       [1.    , 5.    , 0.0755],
       [1.    , 6.    , 0.5998],
       [2.    , 3.    , 0.658 ],
       [2.    , 4.    , 0.0755],
       [2.    , 5.    , 0.4002],
       [2.    , 6.    , 0.0087],
       [3.    , 4.    , 0.5998],
       [3.    , 5.    , 0.0087],
       [3.    , 6.    , 0.2578],
       [4.    , 5.    , 0.7422],
       [4.    , 6.    , 0.0669],
       [5.    , 6.    , 0.658 ]])

In [10]:
caler.decompose(atms=(1,2))

array([[1.1407],
       [0.689 ],
       [0.2142],
       [0.0001]])